# Informações do Projeto
site_name: "Metadados Fiscais MG: Documentação do Painel Fiscal"
site_url: https://vivigoncalvesportonascimento.github.io/site-painel-situacao-fiscal/
#site_url: https://usuario.github.io/fiscaldocs-mg/
site_author: Viviane Gonçalves Porto Nascimento
site_description: >
  Documentação completa sobre a metodologia, fontes de dados e processo de
  desenvolvimento do Painel de Transparência Fiscal de Minas Gerais.

# Repositório
repo_name: vivigoncalvesportonascimento/site-painel-situacao-fiscal
repo_url: https://github.com/vivigoncalvesportonascimento/site-painel-situacao-fiscal
edit_uri: edit/main/docs/


# Configuração do Tema Material
theme:
  name: material
  language: pt
  #logo: assets/logo.svg
  #favicon: assets/favicon.png
  palette:
    # Paleta para modo claro
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    # Paleta para modo escuro
    - scheme: slate
      primary: blue grey
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - content.code.copy

# Estrutura de Navegação (Menus do site)
nav:
  - 'Página Inicial': 'index.md'
  - 'O Projeto':
    - 'Motivação e Objetivos': 'projeto/motivacao.md'
    - 'Ferramentas Utilizadas': 'projeto/ferramentas.md'
  - 'Metodologia de Dados':
    - 'Fontes de Dados': 'dados/fontes_dados.md'
    - 'Pipeline e ETL': 'dados/pipeline_etl.md'
    - 'Frictionless e Datapackage': 'dados/padrao_frictionless.md'
  - 'O Dashboard':
    - 'Desenvolvendo o Painel': 'dashboard/desenvolvendo_painel.md'
    - 'Scripts Centrais': 'dashboard/scripts_centrais.md'
    - 'Scripts dos Indicadores': 'dashboard/scripts_indicadores.md'
    #- 'Guia de Uso': 'dashboard/guia_usuario.md'    
  - 'Comunidade':
    - 'Como Replicar': 'comunidade/como_replicar.md'
    - 'Como Contribuir': 'comunidade/como_contribuir.md'

# Extensões do Markdown para recursos avançados
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      # pygments_style: github      <-- REMOVIDO
      # pygments_style_dark: dracula  <-- REMOVIDO
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html